### ISSUE TITLE
Not possible to log-in to peekaboo using the docker environment

### ISSUE THREAD

**Issue by bleedinge** [SussexLearningSystems/peakaboo#25]
Hi,

I'm trying to test peekaboo and for that checked out the project and switched to develop.

Bringing up the docker environment, and trying to log-in to the web application with the credentials (admin@example.com/admin) fails with no message.

Executing a shell in the mongodb container and checking the DB contents I can see that the sample users have been created properly:

`peakaboo:PRIMARY> db.users.find({})
{ "_id" : "Tj44QMWhxbWxtJwnR", "createdAt" : ISODate("2016-05-26T08:29:56.527Z"), "services" : { "password" : { "bcrypt" : "$2a$10$ifJika9Xhavw6mhj20YVCuNSFfqU4UX9n3HtcfmcTx8B/a6d5VEU." } }, "emails" : [ { "address" : "admin@example.com", "verified" : true } ], "profile" : { "name" : "Admin" }, "roles" : [ "admin" ] }
{ "_id" : "HkyrwqYswXE9kMq8b", "createdAt" : ISODate("2016-05-26T08:29:56.582Z"), "services" : { "password" : { "bcrypt" : "$2a$10$T2jxyDnzO.o90rxJ1I/5WeS2sZADNpFCD/8Puykp/7uLlt4UHQiwm" } }, "emails" : [ { "address" : "view@example.com", "verified" : true } ], "profile" : { "name" : "View" }, "roles" : [ "view-rooms" ] }
{ "_id" : "QHJGMtMoAHnWxwvvb", "createdAt" : ISODate("2016-05-26T08:29:56.639Z"), "services" : { "password" : { "bcrypt" : "$2a$10$pKgP7QcKibsMmUUjFWhoaODe0Q.xd4kaorqgs6nTEvHwN9eWelQPa" } }, "emails" : [ { "address" : "control@example.com", "verified" : true } ], "profile" : { "name" : "Control" }, "roles" : [ "control-rooms" ] }
{ "_id" : "FPaepJLxbwNJaoTnY", "createdAt" : ISODate("2016-05-26T08:29:56.696Z"), "services" : { "password" : { "bcrypt" : "$2a$10$awqQx1MSb485oCDZ35ttweDi8YBj0il1aBuf3kPLjiv6kOS/cHAsm" } }, "emails" : [ { "address" : "galicaster@example.com", "verified" : true } ], "profile" : { "name" : "Galicaster" }, "roles" : [ "galicaster" ] }`

Should this work or did I miss something?

Thanks,
Bruno

**Comment by pmgration** [comment]
Have you got something like the following for the logins section of your settings?

```json
{
  "logins": {
    "loginWithPassword": {
      "active": true
    }
  }
}
...
```

When running in docker these are set as part of the METEOR_SETTINGS environment variable (and quotes need escaping properly - see .docker/README.md)
Or to test you could open the browser console and try `Meteor.loginWithPassword('admin@example.com', 'admin');`, assuming the login worked you should then be able then access the root URL again without getting redirected to the login (it should redirect to /room_list).

**Comment by pmgration** [comment]
I've just noticed we didn't include a sample configuration file so I'll look at adding one soon, there isn't much to it and the above should be all that is required for local logins to work.

**Comment by pmgration** [comment]
Closing this issue as we haven't heard anything further from @bleedinge but we can re-open if needed. I'm assuming the `logins` configuration was all that was required, we also added the example run script for docker deployment a while after this issue was raised.
