### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by bersuitvera** [SussexLearningSystems/peakaboo#46]
Hi Paul
I'm testing peekaboo for my opencast platform 
I see that you create a test user on mongo
Can I use basic authentication with admin/admin?
Should I configure mandatory cas or ldap?

**Comment by androidwiltron** [comment]
Hi
i suppose we should do a bit more docs on this

when you are just developing, you see that some test users are created in the meteor console
so in a web browsers console you can do autentication using the following:
`Meteor.loginWithPassword('admin@example.com','admin')`

in production you shouldn't do this, you can remove the test users all together

**Comment by androidwiltron** [comment]
moreover you can use this settings.json file in development
https://github.com/SussexLearningSystems/peakaboo/blob/master/docs/settings.example.json

i think if you use:

```
"logins":{
      "password":{
         "active":true
      },
```
it would do the same, but ive not tested this for ages sorry!

**Comment by bersuitvera** [comment]
Thanks
 it's  works fine.
